### ISSUE TITLE
Ammo Presets not working

### ISSUE THREAD

**Issue by Bryantdl7** [Weol/URM#2]
![image](https://cloud.githubusercontent.com/assets/5564661/10064046/77e61dbc-6242-11e5-9aa9-4d1eebd4c748.png)

I typed kill in console and respawned to verify this, however I still only spawn with 6 rounds.

**Comment by Weol** [comment]
Hmm, I fail to recreate this. Are you running anything else that might interfere with you ammo?

**Comment by Bryantdl7** [comment]
Do you have any known conflicts with your addon? I can run a single player session with just ulx to try and narrow it down.

**Comment by Weol** [comment]
I have not encountered any addon that conflicts. You you could give me a list of the addons you use, I'm sure I can find it.

Most likely there's an addon that overrides URM's "PlayerSpawn" hooks. That an addon allows the restricted weapons to be spawned, whilst URM says they're restricted. Not use why that addon would have priority over URM, tho.

**Comment by Bryantdl7** [comment]
Well Falcos prop protection can restrict materials and some entities, also I use this addon called buildmode which can prevent the spawning of all weapons when you choose to be put into godmode, maybe that can help some.
I'm sorry I can't help more than some suggestions, I only have my phone currently. 
Gmod prioritizes things in a very disorganized manner from what I've learned.

**Comment by Weol** [comment]
It has to be the build mode, I developed it whilst running Falcos. I'll have a look at it.

**Comment by Weol** [comment]
There seems to be alot of buildmode addons. Could you provide a workshop link or something like that?

**Comment by Bryantdl7** [comment]
Yes, sorry. 
http://steamcommunity.com/sharedfiles/filedetails/?id=372546268
I'm not normally this disorganized I'm just camping currently lol

**Comment by Weol** [comment]
Thank you. It appears that the buildmode addon is using the "PlayerSpawnSWEP" badly:

``` lua
hook.Add("PlayerSpawnSWEP", "TryWepSpawn",  function(ply)
    if (ply:GetNWInt("_kyle_buildmode") == 1) then
        ply:SendLua("GAMEMODE:AddNotify(\"You cannot get weapons while in Build Mode.\",NOTIFY_GENERIC, 5)")
        return false
    else
        return true
    end
end) 
```

As you can see he returns true instead of simply not returning anything, which is bad practice, as it overrides any other "PlayerSpawnSWEP" hooks that are called after it. The only way to make URM run before the buildmode addon is to extract the workshop addon to a normal folder, and renaming it to something "XXXX-buildmode" or something like that. Garrys mod runs addons in alphabetical order, thereby making URM run before the buildmode addon.

**Comment by kythre** [comment]
I'll go fix that. I'm not too experienced with how Garry's Mod functions, and what-not.

Edit: I just uploaded the update, it shouldn't cause that issue anymore.

**Comment by Weol** [comment]
Well hello, I didn't realize you were on Github :+1: 

Anyway, good thing you fixed it. You should do the same with your "PlayerCanPickupWeapon" hook, as it acts the same way.

**Comment by kythre** [comment]
Yeah, I've had this account for a while, I've just never used it.
I'll be sure to change that, thanks for telling me that.

I committed the edit to Github, but I wasn't able to update it on the Workshop because I lost internet, I'm not at home right now so I won't be able to update it on the Steam Workshop until I get home later today,
