### ISSUE TITLE
[Potential Bug] URM may be causing two issues.

### ISSUE THREAD

**Issue by ickycoolboy** [Weol/URM#9]
The first issue is this error that maybe occurs when joining a server with URM installed:
[ERROR] lua/includes/extensions/net.lua:182: net.ReadType: Couldn't read type 120
1. error - [C]:-1
   1. ReadType - lua/includes/extensions/net.lua:182
   2. ReadType - lua/includes/extensions/net.lua:121
      1. ReadType - lua/includes/extensions/net.lua:124
      2. ReadType - lua/includes/extensions/net.lua:124
      3. ReadTable - lua/includes/extensions/net.lua:124
      4. func - addons/ulib/lua/ulib/client/cl_util.lua:9
         1. unknown - lua/includes/extensions/net.lua:32

The second issue is that ulx gettings stuck at "Getting data: Bans" and bans are not able to be viewed.
https://puu.sh/qE8VT/b03589707d.png

There are multiple threads on the ulx forums discussing this issue as well:
http://forums.ulyssesmod.net/index.php/topic,9835.0.html
http://forums.ulyssesmod.net/index.php/topic,9805.0.html
https://forums.ulyssesmod.net/index.php/topic,8967.15.html

It would be awesome if you could look into this. Thanks!

**Comment by Weol** [comment]
Hi, I'm sorry, I should have noticed this days ago, I will look into this and update as soon as possible.

**Comment by Weol** [comment]
Allright, I reworked the networking system so that URM no longer uses ULX's system. So any net related conflicts between ULX and URM should be resolved, unless ULX has made wierd changed to the net library.

**Comment by SticklyMan** [comment]
That would be interesting if it fixes the issue. xgui.sendDataTable uses ULib.clientRPC, which hasn't been modified for a very long time (unless they changed something with net.WriteTable): https://github.com/TeamUlysses/ulib/blob/master/lua/ulib/server/util.lua#L25
We also haven't had any other reports of issues with large amounts of data being sent, so that's weird too. Oh well, hope the fix works out!

**Comment by Weol** [comment]
It appears that the issue was fixed. You should note that only a few people had this problem, I could not replicate it on my local server either. I'm not sure if it was large data that caused it or a bogus entity, but I think the problem was in the data that URM tried to send rather than in ULX's system.

**Comment by SticklyMan** [comment]
Interesting.. Could be an underlying issue with net.WriteTable (which you are not using) and some bad/unique data. We'll keep our eye on it, then! Thanks for your help figuring this out!

**Comment by ickycoolboy** [comment]
Thank you for the fix! I can confirm it worked.
